#!/usr/bin/env node

/**
 * A basic wrapper for autoprefixer.
 * Hand-rolled to avoid Grunt/Gulp/Flavour-of-the-month.
 */

var fs = require('fs-extra'),
    glob = require('glob'),
    path = require('path'),
    helpers = require('./helpers'),
    autoprefixer = require('autoprefixer');

var autoprefixerOpts = { browsers: ['> 1%', 'last 2 versions'] };

glob(helpers.path('*.css'), function (err, files) {
    if (err) return console.error(err);
    files.forEach(function (file) {
        var fileparts = helpers.parts(file);
        var outputpath = helpers.processedPath(file);
        var outputname = path.basename(outputpath);

        var input = fs.readFileSync(file, 'utf-8');
        var output = autoprefixer.process(input, autoprefixerOpts);
        fs.writeFileSync(outputpath, output);
        console.log('prefixed ' + fileparts.filename + fileparts.ext + ' to ' + path.basename(helpers.buildDir) + '/' + outputname);
    });
});
